# Non-exclusive keywords per publication folder (slug). Shown as chips and used as filters.
# Vocabulary order = display order in the Keywords filter.
VOCAB = [
    # requested
    "Zircon", "ID-TIMS", "LA-ICPMS", "Carbonate", "LIP", "Moon", "Earth history",
    "Reference material", "Magma reservoir", "Large eruption", "Caldera", "Ore",
    # proposed additions
    "Petrochronology", "Pluton", "Analytical methods", "Hf isotopes", "Lithium",
    "Paleoclimate", "Yellowstone–Snake River Plain", "Pannonian Basin",
]

KEYWORDS = {
    "14-04-ma-hrabovec-tuff-megabed-subaqueous-deposit": ["Zircon", "Large eruption", "Pannonian Basin"],
    "agespectraanalyst-matlab-based-package-model-zircon-age-distributions": ["Zircon", "ID-TIMS", "Magma reservoir", "Analytical methods"],
    "analytical-strategies-207pb-235u-carbonate-geochronology": ["Carbonate", "ID-TIMS", "LA-ICPMS", "Analytical methods"],
    "bridging-basalts-rhyolites-yellowstone-snake-river-plain-volcanic": ["Magma reservoir", "Yellowstone–Snake River Plain"],
    "completion-lunar-magma-ocean-solidification-4-43-ga": ["Moon", "Zircon", "Hf isotopes"],
    "constraining-timescales-mafic-magmatism-central-karoo-large-igneous": ["LIP", "Zircon", "ID-TIMS", "Earth history"],
    "controls-zircon-age-distributions-volcanic-porphyry-plutonic-rocks": ["Zircon", "ID-TIMS", "Magma reservoir", "Pluton", "Ore", "Analytical methods"],
    "cumulate-recycling-igneous-systems-volcanic-record": ["Magma reservoir", "Large eruption"],
    "eruption-history-columbia-river-basalt-group-constrained-high": ["LIP", "Zircon", "ID-TIMS", "Earth history"],
    "europium-barium-enrichments-compositionally-zoned-felsic-tuffs-smoking": ["Magma reservoir", "Large eruption"],
    "evaluating-potential-rhyolitic-glass-lithium-source-brine-deposits": ["Lithium", "Ore", "Yellowstone–Snake River Plain"],
    "explosive-effusive-transition-within-miocene-fataga-suite-gran": ["Large eruption", "Magma reservoir"],
    "geochronological-geochemical-effects-zircon-chemical-abrasion-insights-single": ["Zircon", "ID-TIMS", "Analytical methods"],
    "geochronological-isotopic-records-crustal-storage-assimilation-wolverine-creek": ["Zircon", "ID-TIMS", "Magma reservoir", "Large eruption", "Caldera", "Yellowstone–Snake River Plain"],
    "groundmass-crystallisation-cooling-rates-lava-like-ignimbrites-greys": ["Large eruption", "Yellowstone–Snake River Plain"],
    "gz7-gz8-two-zircon-reference-materials-sims-u": ["Zircon", "Reference material"],
    "high-precision-u-pb-zircon-dating-identifies-major": ["Moon", "Zircon", "ID-TIMS", "Hf isotopes"],
    "high-precision-zircon-age-spectra-record-dynamics-evolution": ["Zircon", "ID-TIMS", "Magma reservoir", "Caldera", "Pluton"],
    "high-precision-zircon-geochronology-geochemistry-evolved-magmatic-centres": ["LIP", "Zircon", "ID-TIMS", "Pluton"],
    "id-tims-u-pb-geochronology-0-1-level": ["ID-TIMS", "Zircon", "Analytical methods"],
    "interlaboratory-reproducibility-id-tims-u-pb-geochronology-evaluated": ["ID-TIMS", "Zircon", "Analytical methods"],
    "isotope-dilution-anchoring-zircon-reference-materials-accurate-ti": ["Zircon", "Reference material", "Analytical methods"],
    "lateral-magma-propagation-during-emplacement-gloria-pluton-central": ["Pluton", "Zircon"],
    "long-term-repeatability-interlaboratory-reproducibility-high-precision-id": ["ID-TIMS", "Zircon", "Analytical methods"],
    "maturation-rejuvenation-silicic-magma-reservoir-high-resolution-chronology": ["Zircon", "ID-TIMS", "Magma reservoir", "Large eruption", "Caldera", "Petrochronology"],
    "methodologies-176lu-176hf-analysis-zircon-grains-moon-beyond": ["Moon", "Zircon", "Hf isotopes", "Analytical methods"],
    "microid-tims-spatially-resolved-high-precision-u-pb": ["Zircon", "ID-TIMS", "Analytical methods"],
    "mid-miocene-silicic-explosive-volcanism-tokaj-mts-eastern": ["Zircon", "Large eruption", "Pannonian Basin"],
    "modulation-zircon-solubility-crystal-melt-dynamics": ["Zircon", "Magma reservoir"],
    "neogene-plant-macrofossils-west-antarctica-reveal-persistence-nothofagaceae": ["Earth history", "Paleoclimate"],
    "obsidian-pyroclasts-yellowstone-snake-river-plain-ignimbrites-dominantly": ["Large eruption", "Yellowstone–Snake River Plain"],
    "onset-long-lived-silicic-alkaline-magmatism-eastern-north": ["LIP", "Zircon", "ID-TIMS", "Pluton", "Earth history"],
    "pluton-formation-volcanic-plutonic-connection-large-igneous-provinces": ["LIP", "Zircon", "ID-TIMS", "Pluton", "Large eruption", "Magma reservoir"],
    "post-caldera-volcanism-heise-volcanic-field-implications-petrogenetic": ["Caldera", "Zircon", "Magma reservoir", "Yellowstone–Snake River Plain"],
    "post-eruptive-mobility-lithium-volcanic-rocks": ["Lithium", "Yellowstone–Snake River Plain"],
    "primary-petrology-mineralogy-age-letseng-terae-kimberlite-lesotho": ["Earth history"],
    "protracted-near-solidus-storage-pre-eruptive-rejuvenation-large": ["Zircon", "ID-TIMS", "Magma reservoir", "Large eruption", "Caldera", "Petrochronology"],
    "recommendations-reporting-interpretation-isotope-dilution-u-pb-geochronological": ["ID-TIMS", "Zircon", "Analytical methods"],
    "red-bole-zircon-record-cryptic-silicic-volcanism-deccan": ["LIP", "Zircon", "Hf isotopes"],
    "sc-550-sintered-calcite-reference-material-situ-u": ["Carbonate", "Reference material", "LA-ICPMS", "ID-TIMS"],
    "search-missing-half-world-class-copper-resource-chuquicamata": ["Ore", "Zircon", "ID-TIMS", "Pluton"],
    "shifty-toba-magma-reservoir-improved-eruption-chronology-petrochronological": ["Zircon", "ID-TIMS", "Magma reservoir", "Large eruption", "Caldera", "Petrochronology"],
    "sink-sink-thermal-density-structure-modern-northern-andean": ["Zircon", "ID-TIMS"],
    "technical-note-ra138-calcite-u-pb-icp-ms": ["Carbonate", "Reference material", "LA-ICPMS", "ID-TIMS"],
    "timescales-magmatic-hydrothermal-activity-giant-san-rafael-tin": ["Ore", "Zircon", "ID-TIMS"],
    "timing-tempo-organic-carbon-burial-monterey-formation-santa": ["Earth history", "Paleoclimate", "Zircon", "ID-TIMS"],
    "tracing-widespread-early-miocene-ignimbrite-eruptions-petrogenesis-onset": ["Zircon", "Large eruption", "Pannonian Basin"],
    "transminas-pirenopolis-dike-swarms-evidence-central-south-atlantic": ["LIP", "Earth history"],
    "u-pb-geochronology-malokaroy-series-kazakhstan-constrains-global": ["Earth history", "Zircon", "ID-TIMS"],
    "u-pb-id-tims-geochronology-atona-amplifiers": ["ID-TIMS", "Analytical methods"],
    "u-th-zircon-dating-reveals-correlation-eruptive-styles": ["Zircon", "Caldera"],
    "vitoria-dike-swarm-key-piece-puzzle-low-ti": ["LIP"],
    "waning-saxothuringian-ocean-evidenced-famennian-tephra-bearing-siliceous": ["Earth history"],
    "widespread-silicic-alkaline-magmatism-synchronous-deccan-traps-flood": ["LIP", "Zircon", "ID-TIMS"],
    "zircon-geochronology-geochemical-constraints-geometry-solidification-timescales-dufek": ["LIP", "Zircon", "ID-TIMS", "Hf isotopes", "Pluton"],
}
